makerdao/spells-goerli

Makefile
shell.nix
test-dssspell.sh

Uses DssExecLib code tagged to `v0.0.7` release.
I've deployed a new DssExecLib to Goerli because the one that's existing here is pointing to `master`, which is a little different than the `0.0.7` release on mainnet. We should use this code because if there is any issue with using this version we will discover it here before we roll over to prod.

Use DssExecLib code v0.0.7

---

Makefile
archive-dssspell.sh
archive/2022-01-27-DssSpell/Goerli-DssSpell.t.sol
verify.py

Port improvements from Feb 4th mainnet spell

---

scripts/verify.py

- Remove `verify.py` temporary license workaround following etherscan apis license fix (missing n. 13 in license range)

Remove `verify.py` temporary license workaround

---

src/Goerli-DssSpell.t.sol

Fixes the case where new entries are added to the changelog and the version is appropriately updated by short-circuiting the test.

Fix bug in test when new chainlog entries are added and version is changed

---

scripts/wards.sh

- Backporting [makerdao/spells-mainnet@`4459fab` (#249)](https://github.com/makerdao/spells-mainnet/pull/249/commits/4459fab46cf8580df466fb1a152ffb53f5a27ae6)
- Refactor splitting chainlog `list` output via `IFS` in the loop
- Fix `sed` mac issue by replacing it with `tr` (mac seems to come with bash version 3)
- Cleanups

More `wards.sh` refactoring + fix mac `sed` issue

---

src/Goerli-DssSpell.sol
src/test/starknet.t.sol

Add Starknet max deposit rise to PE-1084

---

src/Goerli-DssSpell.sol
src/Goerli-DssSpell.t.sol

Add Teleport feed update to PE-1084

---

src/Goerli-DssSpell.sol
src/Goerli-DssSpell.t.sol
src/test/config.sol

Changes for the PE-1102 Spell that concern the **GUSD PSM**
https://vote.makerdao.com/polling/QmYffkvR#vote-breakdown
https://forum.makerdao.com/t/signal-request-change-psm-gusd-a-parameters/18142

PE-1102: 2022-10-19 Executive GUSD PSM

---

src/Goerli-DssSpell.sol
src/test/addresses_goerli.sol
src/test/starknet.t.sol

feat: add Starknet fee support

---

src/Goerli-DssSpell.sol
src/Goerli-DssSpell.t.sol
src/test/config.sol

[PE-1124] fix(centrifuge/bt): reinstate `ward` access to centrifuge ROOT

---

src/DssSpell.t.sol

Port test of deploy size and update to deploycost test

---

foundry.toml
script/input/5/integration.json
scripts/test-dssspell-forge.sh
src/DssSpell.sol
src/DssSpell.t.base.sol
src/DssSpell.t.sol
src/test/config.sol

Pe 1184 add l2 tests

---

src/DssSpell.t.base.sol

- Proposed fix for #166
Tested:
- block [8451434](https://goerli.etherscan.io/block/8451434) `deployed` PASS
- block [8451989](https://goerli.etherscan.io/block/8451989) `cast` PASS
- block [8451982](https://goerli.etherscan.io/block/8451982) `schedule` PASS

Fix binary search

---

src/DssSpell.t.base.sol
src/DssSpell.t.sol

Port PSM test fix from mainnet

---

scripts/hash-exec-copy.sh

This script currently does not work for anyone whose system is configured to a language that is not English, because `date %B` returns the [locale's full month name](https://man7.org/linux/man-pages/man1/date.1.html).
While this script is not often part of the Goerli spell workflow, there's a [PR on `spells-mainnet`](https://github.com/makerdao/spells-mainnet/pull/340), so we better keep this consistent.

Fix: `make exec-hash` for non-English systems

---

scripts/test-dssspell-forge.sh

The [`--match` flag was finally removed](https://book.getfoundry.sh/reference/forge/forge-test#test-options) from `forge` in favor of `--match-test`/`--match-contract`/`--match-path`.
`make test-forge` script is now broken.

Fix: `make test-forge match="<test>"` is broken

---

src/DssSpell.sol
src/DssSpell.t.base.sol
src/DssSpell.t.sol

Flapper related suggestions

---

.github/workflows/tests.yaml
Makefile
scripts/test-dssspell-forge.sh

Sometimes a spell crafter wants to re-run a couple of tests only for faster execution when using an external JSON RPC provider. For that we have the `match='<regex>'` option.
However there is a case where the crafter might want to run the entire test suite, but skip only the ones that take longer to execute. This can be useful when debugging spells, shortening the feedback loop.
This PR adds the `no-match='<regex>'` options which uses the `--no-match-test` option from `forge` to skip a couple of tests.
For instance, one could skip `testAuth` and `testAuthInSources` while iterating over the spell code and only run those heavy tests at the end:
```bash
make test-forge no-match='testAuth|testAuthInSources'
```

Feature: add `no-match` option to `make test-forge` / Refactor: use `make test` instead of `make test-forge` in CI

---

src/DssSpell.t.base.sol

The `setUp` function was supposed to take care of the scenario when the spell has already been cast using `rollFork`.
However, there seems to be an outstanding [issue](https://github.com/foundry-rs/foundry/issues/5739) on Foundry that prevents the proper setup.
The workaround is to manually overwrite the `eta` storage variable that is being read before using the `vm.store` cheatcode to ensure the spell can be scheduled and cast again.
---
Another small improvement: remove `vm.makePersistent(address(this))` from this function, because it is a superfluous call.
From the [docs](https://book.getfoundry.sh/cheatcodes/make-persistent?highlight=makeper#makepersistent):
> By default, only the test contract account and the caller are persistent across forks

Fix broken tests after casting a spell

---

scripts/cast-dssspell.sh

The script is broken since Foundry introduced an additional output when specifying the return type of the function in the signature:
```bash
cast call "$MCD_GOV" 'balanceOf(address)(uint)' "$ETH_FROM"
```
Now returns:
```
100000000000000000000000 [1e23]
```
Notice the dangling ` [1e23]`.
Previously, it would return simply:
```
100000000000000000000000
```
I'm not entirely sure when this change was introduced, but it must be a recent one, since last time I cast a Goerli spell (late 2023), it worked without any issues.

Fix: cast spell script
