makerdao/spells-goerli

- README.md
- archive/2021-09-22-Add-Gelato-Dai-Vesting-and-others.sol
- archive/2021-09-22-Add-Gelato-Dai-Vesting-and-others.t.sol
- src/Goerli-DssSpell.sol
- src/Goerli-DssSpell.t.sol
> PE-678: MakerDAO September 22, 2021 Görli Executive Spell

- src/Goerli-DssSpell.t.sol
- verify.py
> Temporary Spell Verify Script License Fix

- src/Goerli-DssSpell.t.base.sol
Add dss-interfaces and update dss-exec-lib so we can use `WardsAbstract` and `PsmAbstract` from there
> Update dss interfaces

- Makefile
- archive-dssspell.sh
- src/Goerli-DssSpell.t.base.sol
- src/Goerli-DssSpell.t.sol
- src/test/addresses_deployers.sol
- src/test/addresses_goerli.sol
- src/test/rates.sol
- test-dssspell.sh
Bringing Goerli up to speed with https://github.com/makerdao/spells-mainnet/pull/210
> Spell clean up mainnet 210

- src/Goerli-DssSpell.t.sol
> Add 2 more esm tests

- .gitignore
- Makefile
- test-dssspell.sh
- verify.py
Script changes from the 1/28 Mainnet spell to keep the repos in sync.
> Backport changes from 1/28/2022 mainnet spell

- src/Goerli-DssSpell.t.base.sol
- src/test/config.sol
> Move Spell and System Values to config file

- Makefile
- wards.sh
> `wards.sh`

- src/test/addresses_deployers.sol
> checkWards fix

- Makefile
- scripts/wards.sh
- Include reverse wards check case in `wards.sh` (Target -> Contract)
- Tested with `End` as target
- `make wards target=MCD_END`
- https://hackmd.io/@naszam/SJWRD0sI9
- Refactor `src` wards check
- Tested `src` wards check with `0x1f42e41A34B71606FcC60b4e624243b365D99745` as target
> Include reverse wards check in `wards.sh` + refactoring

- src/Goerli-DssSpell.sol
- src/Goerli-DssSpell.t.base.sol
- src/Goerli-DssSpell.t.sol
- src/Goerli-DssSpellCollateral.sol
- src/test/addresses_deployers.sol
- src/test/addresses_goerli.sol
- src/test/config.sol
- src/test/rates.sol
- template/Goerli-DssSpell.sol
- template/Goerli-DssSpellCollateralOnboarding.sol
- Specify year or file creation (or derived file)
- Cleanup `Copyright (C)` comment
> Fix `SPDX-FileCopyRightText` + Cleanups

- src/Goerli-DssSpell.t.base.sol
- src/Goerli-DssSpell.t.sol
- src/test/addresses_deployers.sol
- src/test/config.sol
The best way to review these changes is to diff them to current spell-mainnet files on master.
> port from spells-mainnet

- src/Goerli-DssSpell.sol
- src/Goerli-DssSpellCollateral.sol
- src/test/config.sol
> Enable autoline for RWA007-A

- Makefile
- scripts/hash-exec-copy.sh
- Add `hash-exec-copy.sh` script to generate exec hash
- `make exec-hash url=https://raw.githubusercontent.com/makerdao/community/...`
- Revert to `curl` in case `wget` is not installed
- Sanity check the expected `url` to match
> `hash-exec-copy.sh`

- scripts/deploy.sh
- Add `ETHERSCAN_API_KEY` check in `deploy.sh`
> Add `ETHERSCAN_API_KEY` check in `deploy.sh`

- src/Goerli-DssSpell.sol
- src/Goerli-DssSpell.t.sol
- src/Goerli-DssSpellCollateral.sol
- src/test/addresses_deployers.sol
- src/test/addresses_goerli.sol
- src/test/config.sol
Updated RETH draft spell for merge into PE-1105
> feat: add goerli reth spell

- src/Goerli-DssSpell.sol
- src/test/starknet.t.sol
> increase Starknet bridge limit

- .gitmodules
- src/DssSpell.t.base.sol
- src/DssSpell.t.sol
- src/test/config.sol
Switch from forge-std/Test.sol to dss-test/DSSTest.sol
Draft until we can merge and update for:
> Add dss-test

- src/test/starknet.t.sol
Tests that a starknet spell is scheduled in starknet core after cast
> Test that starknet spell is scheduled in core

- src/DssSpell.sol
- src/DssSpell.t.sol
> Adding Spark GNO onboarding
